version: '3'
services:
  # Mongodb
  mongo:
    image: mongo:4.2
    volumes:
      - C://Users/ASUS/Desktop/graylog/users:/data/db
    networks:
      - graylog
  # elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    volumes:
      - C://Users/ASUS/Desktop/graylog/log:/usr/share/elasticsearch/data
    environment:
      - http.host=0.0.0.0
      - transport.host=localhost
      - network.host=0.0.0.0
      - "ES_JAVA_OPTS=-Dlog4j2.formatMsgNoLookups=true -Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 1g
    networks:
      - graylog
  # graylog
  graylog:
    image: graylog/graylog:4.2
    environment:
      - GRAYLOG_PASSWORD_SECRET=somerandompassword
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:9000/
    entrypoint: /usr/bin/tini -- wait-for-it elasticsearch:9200 --  /docker-entrypoint.sh
    networks:
      - graylog
    restart: always
    depends_on:
      - mongo
      - elasticsearch
    ports:
      # graylog web interface and rest api
      - 9000:9000
      # syslog tcp
      - 1514:1514
      #syslog udp
      - 1514:1514/udp
      # GELF tcp
      - 12201:12201
      # GELF UDP
      - 12201:12201/udp
    # volumes:
    #   - C://Users/ASUS/Desktop/graylog/journal:/usr/share/graylog/data/journal
    #   - C://Users/ASUS/Desktop/graylog/config:/usr/share/graylog/data/config
networks:
  graylog:
    driver: bridge